#!/usr/bin/python


import sys
from scapy.all import *
print """
Run as root 
Make sure card in monitor mode

"""
def PacketHandler(pkt) :
	if pkt.haslayer(Dot11):
		if pkt.type == 0 and pkt.subtype == 4 : 
			if pkt.info :
				print "SSID: {} MAC: {}".format(pkt.info, pkt.addr2)
if len(sys.argv)<2:
	print "Usage ./sssid.py <iface>"
else:	sniff(iface=sys.argv[1], prn=PacketHandler)
